repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: double-quote-string-fixer
          - id: requirements-txt-fixer
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.7
